# Conversation states
(
    REGISTER_NAME,
    REGISTER_EMAIL,
    ADD_AMOUNT,
    ADD_DESCRIPTION,
    ADD_CATEGORY,
    ADD_CATEGORY_CUSTOM,
    ADD_PAID_BY,
    ADD_SPLIT_TYPE,
    ADD_MEMBERS,
    ADD_CUSTOM_AMOUNTS,
    ADD_CUSTOM_PERCENT,
    CONFIRM_EXPENSE,
    SETTLE_SELECT_RECEIVER,
    SETTLE_ENTER_AMOUNT,
    SETTLE_CONFIRM,
) = range(15)
